version: "3.9"

services:
  redis:
    image: bitnami/redis:7.0.8
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "${REDIS_PORT}:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "${REDISINSIGHT_PORT}:8001"