version: "3.9"

services:
  redis:
    image: redis:7.2.4
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "${REDIS_PORT}:6379"
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "${REDISINSIGHT_PORT}:5540"
